export const JUDGE_QUEUE = Symbol('JUDGE_QUEUE');
export const JUDGE_QUEUE_EVENTS = Symbol('JUDGE_QUEUE_EVENTS');
export const GOLDEN_VERIFY_QUEUE = Symbol('GOLDEN_VERIFY_QUEUE');
export const GOLDEN_VERIFY_QUEUE_EVENTS = Symbol('GOLDEN_VERIFY_QUEUE_EVENTS');
export const CALIBRATE_LIMITS_QUEUE = Symbol('CALIBRATE_LIMITS_QUEUE');
export const CALIBRATE_LIMITS_QUEUE_EVENTS = Symbol('CALIBRATE_LIMITS_QUEUE_EVENTS');
export const REDIS_CONNECTION = Symbol('REDIS_CONNECTION');
export const REPORT_EXPORT_QUEUE = Symbol('REPORT_EXPORT_QUEUE');

